# Problem Statement:-
### Minimum Spanning Tree

In [1]:
import numpy as np
matrix=[]
n=int(input("Enter the number of nodes: "))
for i in range(n):
    a=[]
    for j in range(n):
        val=int(input("Enter value for edge between "+str(i)+" and "+str(j)+" :"))
        a.append(val)
    matrix.append(a)
arr=np.array(matrix)
print(arr)
# matrix = []
# row = 4
# nodes = 4

# matrix = [
#     [99,2,5,3],
#     [2,99,99,7],
#     [5,99,99,8],
#     [3,7,8,99]
# ]

Enter the number of nodes: 4
Enter value for edge between 0 and 0 :99
Enter value for edge between 0 and 1 :2
Enter value for edge between 0 and 2 :5
Enter value for edge between 0 and 3 :3
Enter value for edge between 1 and 0 :2
Enter value for edge between 1 and 1 :99
Enter value for edge between 1 and 2 :99
Enter value for edge between 1 and 3 :7
Enter value for edge between 2 and 0 :5
Enter value for edge between 2 and 1 :99
Enter value for edge between 2 and 2 :99
Enter value for edge between 2 and 3 :8
Enter value for edge between 3 and 0 :3
Enter value for edge between 3 and 1 :8
Enter value for edge between 3 and 2 :7
Enter value for edge between 3 and 3 :99
[[99  2  5  3]
 [ 2 99 99  7]
 [ 5 99 99  8]
 [ 3  8  7 99]]


In [2]:
notVisited = []
for i in range(n):
    notVisited.append(i)
visited = []
q = -1
start =int(input("Enter the starting node : "))
cost = 0
visited.append(start)
notVisited.pop(start)
def MST(cost):

    mini = 9999
    for i in visited:
        for j in notVisited:

            if (matrix[i][j] != 99 and mini > matrix[i][j]) :
                mini = matrix[i][j]
                q = j

    cost = cost + mini
    print("minimum value selected = ",mini)
    print("Total cost = ",cost)
    print("endNode selected = ",q)
    visited.append(q)
    notVisited.remove(q)
    if notVisited:
        MST(cost)

MST(cost)


Enter the starting node : 2
minimum value selected =  5
Total cost =  5
endNode selected =  0
minimum value selected =  2
Total cost =  7
endNode selected =  1
minimum value selected =  3
Total cost =  10
endNode selected =  3
